name: Build and Deploy Production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodeModules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn react-app:build
        env:
          CI: true
          #REACT_APP_FOREIGN_RPC_URL: https://mainnet.blockscout.com/
          REACT_APP_INFURA_ID: ${{ secrets.INFURA_ID }}
          REACT_APP_HOME_CHAIN_ID: 100
          REACT_APP_FOREIGN_CHAIN_ID: 1
          REACT_APP_HOME_RPC_URL: https://rpc.xdaichain.com/
          REACT_APP_ENABLE_REVERSED_BRIDGE: false
          REACT_APP_DEBUG_LOGS: false
          REACT_APP_TITLE: OmniBridge - %c
          REACT_APP_DESCRIPTION: 'The OmniBridge multi-token extension for the Arbitrary Message Bridge between Ethereum and the xDai chain is the simplest way to transfer ANY ERC20/ERC677/ERC827 token to the xDai chain.'
          REACT_APP_GAS_PRICE_SUPPLIER_URL: https://gasprice.poa.network/
          REACT_APP_GAS_PRICE_SPEED_TYPE: fast
          REACT_APP_GAS_PRICE_UPDATE_INTERVAL: 60000
          REACT_APP_ETH_PRICE_API_URL: 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=USD'
          REACT_APP_ETH_PRICE_UPDATE_INTERVAL: 15000
          REACT_APP_GRAPH_HEALTH_UPDATE_INTERVAL: 60000

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project xdai
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
